networks:
  winter-survival-network:
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - database
      - tailwind
    develop:
      watch:
        - action: sync
          ignore:
            - .phpunit.cache/
            - composer.json
            - composer.lock
            - bootstrap/cache/
            - logs/
            - storage/app/public/
            - vendor/
          path: ./app
          target: /var/www/html
    environment:
      - APP_COOKIE_CONSENT_REQUIRED=${APP_COOKIE_CONSENT_REQUIRED:-true}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_ENV=${APP_ENV:-local}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE:-en_US}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-en}
      - APP_KEY=${APP_KEY:-base64:cHwm2CQU6blIDc2jFEguZ6o81FjoTX627N3dj5fLQBg=}
      - APP_LOCALE=${APP_LOCALE:-en}
      - APP_NAME=${APP_NAME:-winter-survival}
      - APP_SECURE_CONTEXT=${APP_SECURE_CONTEXT:-false}
      - APP_TIMEZONE=${APP_TIMEZONE:-UTC}
      - APP_URL=${APP_URL:-http://localhost:3333}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_DATABASE=${DB_DATABASE:-winter-survival}
      - DB_HOST=${DB_HOST:-database}
      - DB_PASSWORD=${DB_PASSWORD:-winter-survival}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-winter-survival}
      - GOOGLE_ANALYTICS_MEASUREMENT_ID=${GOOGLE_ANALYTICS_MEASUREMENT_ID}
      - GOOGLE_IDENTITY_CLIENT_ID=${GOOGLE_IDENTITY_CLIENT_ID}
      - GOOGLE_IDENTITY_CLIENT_SECRET=${GOOGLE_IDENTITY_CLIENT_SECRET}
      - LOG_CHANNEL=${LOG_CHANNEL:-stack}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL:-null}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_STACK=${LOG_STACK:-single}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
    networks:
      - winter-survival-network
    ports:
      - "3333:8000"
    volumes:
      - ./app/composer.json:/var/www/html/composer.json
      - ./app/composer.lock:/var/www/html/composer.lock
      - ./app/logs/php.log:/var/log/fpm-php.www.log
      - ./app/storage/:/var/www/html/storage

  database:
    build: ./database
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-winter-survival}
      - MYSQL_PASSWORD=${DB_PASSWORD:-winter-survival}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_USER=${DB_USERNAME:-winter-survival}
    networks:
      - winter-survival-network
    volumes:
      - ./database/data:/var/lib/mysql

  tailwind:
    build:
      context: ./app
      dockerfile: Dockerfile.tailwind
    develop:
      watch:
        - action: sync
          path: ./app/public/scripts
          target: /home/node/app/public/scripts
        - action: sync
          ignore:
            - css/
            - js/
          path: ./app/resources
          target: /home/node/app/resources
        - action: sync+restart
          path: ./app/tailwind.config.js
          target: /home/node/app/tailwind.config.js
    networks:
      - winter-survival-network
    tty: true
    volumes:
      - ./app/public/styles/:/home/node/app/public/styles
